spring:
  application:
    name: itoken-admin
  zipkin:
    base-url: http://47.95.112.208:9411

server:
  port: 8084

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
        #include: ["health","info"]

eureka:
  client:
    service-url:
      defaultZone: http://47.95.112.208:8761/eureka/