spring:
  application:
    name: itoken-zipkin
  boot:
    admin:
      client:
        url: http://47.95.112.208:8084
  zipkin:
    base-url: http;//47.95.112.208:9411

server:
  port: 9411

eureka:
  client:
    service-url:
      defaultZone: http://47.95.112.208:8761/eureka/,http://47.95.112.208:8861/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false
  endpoint:
    health:
      show-details: always
    endpoints:
      web:
        exposure:
          include: health,info